# Generated by Django 4.0.1 on 2022-01-23 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbPeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('port', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DbTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recv_transactions', to='bit_torrent.dbpeer')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_transactions', to='bit_torrent.dbpeer')),
            ],
        ),
        migrations.CreateModel(
            name='DbFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('peers', models.ManyToManyField(related_name='files', to='bit_torrent.DbPeer')),
            ],
        ),
    ]
